### ISSUE TITLE
Android compilation problem

### ISSUE THREAD

**Issue by geezmo** [remobile/react-native-splashscreen#2]
Hello,
i'm having issues with Android - the compilation fails with this error:

```
A problem occurred evaluating project ':react-native-splashscreen'.
> Project with path ':react-native-cordova' could not be found in project ':react-native-splashscreen'.
```

If i remove compile project(':react-native-cordova') from the module's own build.gradle everything works.

**Comment by fov42550564** [comment]
the problem solved, thank you very much!
