### ISSUE TITLE
Original splash (green) can be seen for a brief moment when app launches

### ISSUE THREAD

**Issue by bitsofparag** [remobile/react-native-splashscreen#4]
When the app is launching, I can see the original splash image (the sample green colored one) for a split second before it is replaced by my splash image. Any ideas why this happens?

**Comment by bitsofparag** [comment]
Never mind. I replaced the splash.png file from LaunchScreen.xib

**Comment by robtg4** [comment]
@paragmajum Where is the splash.png file in the xcode project once you delete LaunchScreen.xib?

**Comment by bitsofparag** [comment]
@robtg4 In `node_modules/@remobile/react-native-splashscreen`

**Comment by robtg4** [comment]
In the xcode file? I see his original gif but no png

**Comment by bitsofparag** [comment]
So, here's what I did:
1. Delete your original project LaunchScreen.xib
2. Import new LaunchScreen.xib into the project workspace from `<your project>/node_modules/@remobile/react-native-splashscreen/ios/RCTSplashScreen/SplashScreenResource`
3. Make sure you select this new LaunchScreen.xib as the `Launch Screen File` in 'General` settings of your target
4. Open this new LaunchScreen.xib in XCode and replace the splash file (with any extension - jpg or png)

**Comment by robtg4** [comment]
So you "Add New Files" to the Target Folder and have "Launch Screen File" like so:
![screen shot 2015-12-14 at 10 59 45 am](https://cloud.githubusercontent.com/assets/13613075/11785905/d98d494c-a251-11e5-9577-598cc105026d.png)

And then opening the new LaunchScreen.xib I see this: 
![screen shot 2015-12-14 at 11 00 39 am](https://cloud.githubusercontent.com/assets/13613075/11785921/f1055c0e-a251-11e5-9505-89c009110cf8.png)

I do now see where the splash.png is at (in the node modules folder) but now my splash screen is just white.
![screen shot 2015-12-14 at 11 00 39 am](https://cloud.githubusercontent.com/assets/13613075/11785992/3904bf68-a252-11e5-864d-2f4529102489.png)

**Comment by bitsofparag** [comment]
Hope this helps:
<img width="1396" alt="screenshot" src="https://cloud.githubusercontent.com/assets/208331/11786181/89dfcec2-a285-11e5-9287-dd4b0e7f5300.png">

**Comment by robtg4** [comment]
Perfect! Much appreciated!!! Thanks again!

**Comment by robtg4** [comment]
Ok now the launch screen won't hide - and i've included the following code to do so:

```
//register on both android and ios index.js files
var React = require('react-native');
var Parse = require('parse/react-native');
var SplashScreen = require('@remobile/react-native-splashscreen');
var {
    View, 
    StyleSheet, 
    Text, 
    Navigator,
    StatusBarIOS,
} = React;

//authentication components 
var Signin = require('./components/authentication/signin');
var Launch = require('./components/authentication/launch');
var Signup = require('./components/authentication/signup');
var Home = require('./components/experience/home');
var Onboarding = require('./components/authentication/onboarding');
var Introduction = require('./components/authentication/introduction');
var ArticleDetails = require('./components/experience/exp_base_components/article-details.js');

//we have router flux enabled and react-native-navbar but we
//need time to change a few things around to enable more customized 
//component transitions 
var ROUTES ={
    //relates to imported component to display
    //initial route is am object with the name of the route within this variable
    launch: Launch,
    signin: Signin, 
    signup: Signup,
    introduction: Introduction,
    onboarding: Onboarding,  
    home: Home, 
    articledetails: ArticleDetails, 
}

module.exports = React.createClass({
    componentWillMount: function() {
        //executed when component shows on screen
        //tells app to initialize parse and facebook js sdk
        Parse.initialize("jspeQAWhXjb9QAIKxfVbxnggnMv3Y4RuRJ13YLDY", "1IlLlb7x3mHq1vm80zlFlqcoydFuZUQqmjvvmXze");
        //Parse.User.enableRevocableSession();
        return StatusBarIOS.setStyle(1);
    }, 
    componentDidMount: function() {
        SplashScreen.hide();
    }, 
    renderScene: function(route, navigator) {
        //when navigator is initially shown it has to render initial route 
        //render a component and return it, whatever we return is placed on stack
        //add navigator property into this component for all app access
        var Component = ROUTES[route.name]; //ROUTE['signin'] => Signin
        return <Component route={route} navigator={navigator} />;
    }, 
    transition: function(route) {
        return ROUTES[route.name].transition;
    },
    render: function() {
        return (
            <Navigator 
                style={styles.container}
                initialRoute={{name: 'launch'}}
                renderScene={this.renderScene}
                configureScene={ () => { return Navigator.SceneConfigs.FloatFromRight; }} />
        );
    }
});

var styles = StyleSheet.create({
    container: {
        flex: 1,
    }
});
```

**Comment by bitsofparag** [comment]
Did you add launchscreen to AppDelegate as instructed in the README? Since, this launchscreen is the starting screen, you need to add React's root view controller to the splash screen controller:
`[RCTSplashScreen show:rootView];`

**Comment by robtg4** [comment]
Yeah - i found out what it was - conflicting code within the appdelegate.m file - thanks again!! Really appreciate the help!
