### ISSUE TITLE
SplashScreen.hide(); Not Recognized

### ISSUE THREAD

**Issue by robtg4** [remobile/react-native-splashscreen#5]
My simulator is saying that it doesn't know what SplashScreen.hide(); is, and is saying SplashScreen = Undefined (can perform .hide() of undefined). I followed your installation instructions as well - would love assistance if possible! Also, the instructions weren't very clear on replacing the splash.png. Where exactly is it? Do I rename the replacement file the same thing?

**Comment by robtg4** [comment]
Figured it out!!

**Comment by peterwilli** [comment]
@robtg4 I have the same issue, what did you do?

**Comment by robtg4** [comment]
Just Uninstaller everytging and meticulously follow the install instructions, particularly the parts dealing with xcode. Let me know if it doesn't work again and I can help you if you give me access to your repo.

**Comment by peterwilli** [comment]
Yeah it did work for me, propably some old version stuck there. Not sure what happened.
